# Generated by Django 4.0 on 2023-03-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_sermon_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=200)),
                ('flier', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
